# Generated by Django 2.1 on 2018-10-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='update',
            new_name='updated',
        ),
    ]
