# Generated by Django 2.1 on 2018-10-13 21:41

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='E:\\Ahmed\\Ecommerce Web App 2\\static_cdn\\protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
